### ISSUE TITLE
problem with corruption pit thing

### ISSUE THREAD

**Issue by Albirmsam** [Fargowilta/BothEvils#3]
The world gen gets stuck when loading the corruption pit.

**Comment by Fargowilta** [comment]
fixed this update

**Comment by jackfang888** [comment]
Problem not fixed but I believe the problem lies with TML's implementation of worldgen because it can hang right after placing the Orb Heart tiles regardless of if this mod is enabled or not.
